version: "3"
services:
  api:
    build: 
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - broker
      - db
    links:
      - broker
      - db
    environment:
      CATALOG_PATH: /code/app/resources/catalogs/catalog.yaml
      POSTGRES_DB: dds
      POSTGRES_USER: dds
      POSTGRES_PASSWORD: dds
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432       
    volumes:
      - downloads:/downloads:ro 
    command: ["./wait-for-it.sh", "broker:5672", "--",  "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
  executor:
    build: 
      context: ./
      dockerfile: ./executor/Dockerfile
    depends_on:
      - broker
      - db
    links:
      - broker
      - db
    ports:
      - 8787:8787
    environment:
      EXECUTOR_TYPES: query,info,estimate
      CATALOG_PATH: /code/app/resources/catalogs/catalog.yaml
      POSTGRES_DB: dds
      POSTGRES_USER: dds
      POSTGRES_PASSWORD: dds
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432 
    volumes:
      - downloads:/downloads:rw  
    command: ["./wait-for-it.sh", "broker:5672", "--", "python", "./app/main.py"]
  broker:
    image: rabbitmq:3
  db:
    image: postgres:14.1
    restart: always
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dds
      POSTGRES_USER: dds
      POSTGRES_PASSWORD: dds
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  web:
    build: 
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
    environment:
      CATALOG_PATH: /code/app/resources/catalogs/catalog.yaml
      POSTGRES_DB: dds
      POSTGRES_USER: dds
      POSTGRES_PASSWORD: dds
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432       
    volumes:
      - downloads:/downloads:ro 
    command: ["./wait-for-it.sh", "broker:5672", "--",  "uvicorn", "web.main:app", "--host", "0.0.0.0", "--port", "80"]      

volumes:
  downloads: