version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dds
      - POSTGRES_PASSWORD=dds
      - POSTGRES_DB=dds
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  restore-db:
    image: rg.fr-par.scw.cloud/geodds-production/backup:v0.1a2
    depends_on:
      db:
        condition: service_healthy
    command:
      - /bin/bash
      - -c
      - |
        /db_init/restore.sh
        tail -f /dev/null
    volumes:
      - ./db_init:/db_init
    environment:
      - POSTGRES_HOST=db
      - FILENAME=postgres_localhost-2024_10_03_09_53_46-dump-blank.sql
      - POSTGRES_USER=dds
      - POSTGRES_PASSWORD=dds
      - POSTGRES_DB=dds

  catalog:
    image: rg.fr-par.scw.cloud/geolake/geolake-datastore:latest
    build: ./datastore
    volumes:
      - ./catalog:/catalog
    command:
      - /bin/bash
      - -c
      - |
        trap : TERM INT
        sleep infinity &
        wait

  api:
    image: geolago-api:dev
    build: ./api
    command:
      - ./../wait-for-it.sh
      - $(BROKER_SERVICE_HOST):5672
      - --
      - uvicorn
      - main:app
      - --host
      - 0.0.0.0
      - --port
      - '80'
    environment:
      - DB_SERVICE_HOST=db
      - DB_SERVICE_PORT=5432
      - BROKER_SERVICE_HOST=broker
      - POSTGRES_USER=dds
      - POSTGRES_PASSWORD=dds
      - POSTGRES_DB=dds
      - CATALOG_PATH=/catalog/catalog.yaml
      - CACHE_PATH=/catalog/.cache
      - MESSAGE_SEPARATOR='\'
    volumes:
      - ./catalog:/catalog
      - ./downloads:/downloads
      - ./catalog/datasets:/data
    expose:
      - '8080'
    ports:
      - '8080:80'

  broker:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672

  executor:
    image: geolago-executor:dev
    build: ./executor
    command:
      - ./../wait-for-it.sh
      - $(BROKER_SERVICE_HOST):5672
      - --
      - python
      - main.py
    environment:
      - BROKER_SERVICE_HOST=broker
      - DB_SERVICE_HOST=db
      - DB_SERVICE_PORT=5432
      - POSTGRES_USER=dds
      - POSTGRES_PASSWORD=dds
      - POSTGRES_DB=dds
      - EXECUTOR_TYPES=query
      - MESSAGE_SEPARATOR='\'
      - SLEEP_SEC=10
      - RESULT_CHECK_RETRIES=360
      - CATALOG_PATH=/catalog/catalog.yaml
      - CACHE_PATH=/catalog/.cache
      - HDF5_USE_FILE_LOCKING='FALSE'
      - LD_LIBRARY_PATH=/urs/lib/x86_64-linux-gnu
    volumes:
      - ./catalog:/catalog
      - ./downloads:/downloads
      - ./catalog/datasets:/data