name: t3
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.20
  - xarray=2022.6.0
  - geopandas=0.9.0
  - netcdf4=1.6.0
  - pandas=1.4.3
  - dask
  - distributed
  - cartopy
  - xesmf
  - psycopg2
  - bokeh=2.4.2
  # - scipy
  # - plotly
  # - cf_units
  # - hvplot
  # - shapely
  # - metpy
  # - pyarrow
  # - pytest-cov
  # - pytest