apiVersion: v1
kind: Service
metadata:
  namespace: geodds
  labels:
    geodds.service: broker
  name: broker
spec:
  ports:
    - name: "broker"
      port: 5672
      targetPort: 5672
    - name: "http"
      port: 8080
      targetPort: 15672 
  selector:
    geodds.service: broker
  type: LoadBalancer
