apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: geodds
  labels:
    geodds.service: db-claim0
  name: db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
