apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geodds
  labels:
    geodds.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      geodds.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        geodds.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dds
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: user_psw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: user_name
          image: postgres:14.1
          name: db
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: db-claim1
      restartPolicy: Always
      volumes:
        - name: db-claim1
          persistentVolumeClaim:
            claimName: db-claim1
