apiVersion: v1
kind: Service
metadata:
  namespace: geodds
  labels:
    geodds.service: db
  name: db
spec:
  ports:
    - name: "db"
      port: 5432
      targetPort: 5432
  selector:
    geodds.service: db
