apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: geodds
  labels:
    geodds.service: downloads
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
