apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    geodds.service: executor
  name: executor
  namespace: geodds
spec:
  replicas: 1
  selector:
    matchLabels:
      geodds.service: executor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        geodds.service: executor
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - broker:5672
        - --
        - python
        - ./app/main.py
        env:
        - name: RESULT_CHECK_RETRIES
          value: '3'
        - name: DASK_N_WORKERS
          value: '2'
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: CATALOG_PATH
          value: /catalog/catalog.yaml
        - name: CACHE_PATH
          value: /cache
        - name: EXECUTOR_TYPES
          value: query
        - name: POSTGRES_DB
          value: dds
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_PASSWORD
          value: dds
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: dds
        - name: DASK_DASHBOARD_PORT
          value: '8787'
        image: rg.nl-ams.scw.cloud/dds-production/geodds-executor:v0.1a93
        name: executor
        ports:
        - containerPort: 8787
        resources:
          limits:
            cpu: '4'
            memory: 16Gi
          requests:
            cpu: '4'
            memory: 16Gi
        volumeMounts:
        - mountPath: /catalog
          name: catalog
          readOnly: false
        - mountPath: /work/services/dds/DDS-2.0/cache
          name: cache
          readOnly: false
        - mountPath: /data
          name: data
          readOnly: true
        - mountPath: /downloads
          name: downloads
      imagePullSecrets:
      - name: scalereg
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /work/services/dds/DDS-2.0/catalog/Catalog
        name: catalog
      - hostPath:
          path: /work/services/dds/DDS-2.0/downloads
        name: downloads
      - hostPath:
          path: /work/services/dds/DDS-2.0/cache
        name: cache
      - hostPath:
          path: /data
        name: data
