apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geodds
  labels:
    geodds.service: executor
  name: executor
spec:
  replicas: 1
  selector:
    matchLabels:
      geodds.service: executor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        geodds.service: executor
    spec:
      containers:
        - args:
            - ./wait-for-it.sh
            - broker:5672
            - --
            - python
            - ./app/main.py
          env:
            - name: CATALOG_PATH
              value: /catalog/catalog.yaml
            - name: CACHE_PATH
              value: /cache
            - name: EXECUTOR_TYPES
              value: query
            - name: POSTGRES_DB
              value: dds
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PASSWORD
              value: dds
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: dds
          image: rg.fr-par.scw.cloud/ddsr/geodds-executor:v0.1a1
          name: executor
          ports:
            - containerPort: 8787
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "4"
          volumeMounts:
            - mountPath: /catalog
              name: catalog
              readOnly: true
            - mountPath: /cache
              name: cache
              readOnly: true  
            - mountPath: /data
              name: data
              readOnly: true            
            - mountPath: /downloads
              name: downloads
      imagePullSecrets:
          - name: scalereg
      restartPolicy: Always
      volumes:
        - name: catalog
          hostPath:
            path: /work/services/dds/dds-catalog/Catalog
        - name: downloads
          hostPath:
            path: /work/services/dds/downloads
        - name: cache
          hostPath:
            path: /work/services/dds/cache
        - name: data
          hostPath:
            path: /data