apiVersion: v1
kind: Service
metadata:
  namespace: geodds
  labels:
    geodds.service: web
  name: web
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    geodds.service: web
  type: LoadBalancer
  