apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    geodds.service: web
  name: web
  namespace: geodds
spec:
  replicas: 1
  selector:
    matchLabels:
      geodds.service: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        geodds.service: web
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - broker:5672
        - --
        - uvicorn
        - app.main:app
        - --proxy-headers
        - --host
        - 0.0.0.0
        - --port
        - '80'
        env:
        - name: LOGGING_LEVEL
          value: INFO
        - name: CATALOG_PATH
          value: /catalog/catalog.yaml
        - name: POSTGRES_DB
          value: dds
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_PASSWORD
          value: dds
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: dds
        - name: API_URL
          value: http://ddshub.cmcc.it/api
        - name: ENDPOINT_PREFIX
          value: /web
        image: rg.fr-par.scw.cloud/ddsr/geodds-web:v0.1a240
        name: web
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 4Gi
        volumeMounts:
        - mountPath: /catalog
          name: catalog
          readOnly: true
        - mountPath: /work/services/dds/cache
          name: cache
          readOnly: false
        - mountPath: /data
          name: data
          readOnly: true
      imagePullSecrets:
      - name: scalereg
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /work/services/dds/dds-catalog/Catalog
        name: catalog
      - hostPath:
          path: /work/services/dds/cache
        name: cache
      - hostPath:
          path: /data
        name: data
