apiVersion: v1
kind: Service
metadata:
  namespace: development
  labels:
    geoddds.component: wps
  name: wps
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    geodds.component: wps
  type: ClusterIP
