name: Build Docker image of the geodds-api component and push to the production repository

on:
  push:
    tags:        
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get release tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Login to Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }}  | docker login ${{ secrets.DOCKER_PROD_REPO_URL }} -u nologin --password-stdin      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_PROD_REPO_URL }}/geodds-api:${{ env.RELEASE_TAG }}
          ${{ secrets.DOCKER_PROD_REPO_URL }}/geodds-api:latest   
